package org.drools.game.horserace;
import org.drools.game.core.api.*;
import org.drools.game.model.api.*;
import org.drools.game.horserace.model.*;

global GameMessageService messageService;
global GameCallbackService callback;

rule "Greeter"
    when
        $player : Player()
    then
        insert(  messageService.newGameMessage(  "Welcome, " + $player.getName() + ". Venture forth to the stables and mount a mighty steed!" ) );
end

rule "start the race"
        when
            $player : Player()
            $checkpoint : Checkpoint(id == "StartFinish" && !(required.playersCrossedCheckpoint contains $player.getName()))
        then
            insert(  messageService.newGameMessage(  "Contestant " + $player.getName() + ", mount your horse, get ready to race! Three... Two... One... aaaand... GO!" ) );
end

rule "general checkpoint"
        lock-on-active true
        when
            $player : Player()
            $checkpoint : Checkpoint(required.playersCrossedCheckpoint contains $player.getName())
        then
            modify($checkpoint) { addPlayer($player.getName()) }
            insert(  messageService.newGameMessage(  "Contestant " + $player.getName() + ", mount your horse, get ready to race! Three... Two... One... aaaand... GO!" ) );
end

rule "win the race"
        when
            $player : Player()
            $checkpoint : Checkpoint(id == "StartFinish" && required.playersCrossedCheckpoint contains $player.getName())
        then
            insert(  messageService.newGameMessage(  "Contestant " + $player.getName() + " has crossed the finish line! Way to go! Now resetting the race for another attempt. " ) );
end